image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm run test  # скрипт тестирования

# environment:
#   access_token:
#     secure: vhsyHRkml8kIy+qqtqrWvbLWiTCWE2GK1LZCLL6d0nB91N5Z2kjNFQwxHRU+55/C

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  # - git config --global user.name "Remezov Dmitriy"
  # - git config --global user.email "darknessdizi@gmail.com"
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
